### ISSUE TITLE
Does not start with error "env: ‘zypak-wrapper’: No such file or directory"

### ISSUE THREAD

**Issue by langfingaz** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#143]
***What steps will reproduce the issue?***
1\. Install IntelliJ IDEA Ultimate as flatpak from <https://flathub.org/apps/com.jetbrains.IntelliJ-IDEA-Ultimate>
2\. Run it with `flatpak run com.jetbrains.IntelliJ-IDEA-Ultimate`

***What is the expected result?***

The application should start.

***What happens instead?***

The application does not start, instead I get this output on my terminal:

```
idea-wrapper: Setting up NPM packages
idea-wrapper: Setting up Cargo packages
idea-wrapper: Setting up Python packages
idea-wrapper: Setting up Ruby packages
env: ‘zypak-wrapper’: No such file or directory
```

* My system is a fresh installation of Arch Linux (EndeavourOS) with GNOME (X11).
* Flatpak version: `1:1.15.4-1`
* Kernel: `6.2.12-arch1-1`

If I can provide additional helpful information, please let me know.

**Comment by langfingaz** [comment]
This is the version `flatpak list` returns:

```
IntelliJ IDEA Ultimate                     com.jetbrains.IntelliJ-IDEA-Ultimate      2023.1         stable           system
```

**Comment by brittyazel** [comment]
This is because of the re-sync this morning with jetbrains-flatpak-wrapper. The version in-question had pulled in a zypak depency last week, which was reverted about an hour ago. We just need someone on this repo (and the others) to resync with jetbrains-flatpak-wrapper upstream and trigger a rebuild/redeploy.

For the time being you can roll back to the previous build:
flatpak remote-info --log flathub com.jetbrains.IntelliJ-IDEA-Ultimate

Grab the commit ID from the second the last version, and then downgrade with:
sudo flatpak update --commit=<commit-id-here> com.jetbrains.IntelliJ-IDEA-Ultimate

**Comment by langfingaz** [comment]
Many thanks!

**Comment by x80486** [comment]
Should be done once I merge `144` — as always, a pull request is welcomed once you know how to solve the issue(s) :wink:
