### ISSUE TITLE
Provide distributions with Gnome and KDE runtimes.

### ISSUE THREAD

**Issue by weisJ** [flathub/com.jetbrains.IntelliJ-IDEA-Ultimate#58]
During the investigation of [this bug-report](https://github.com/weisJ/auto-dark-mode/issues/20) it was discovered that the flatpak distribution of IntelliJ doesn't offer Gnome specific libraries. It would be great to have specialised distributions with the Gnome (repsectively KDE) runtime.

**Comment by x80486** [comment]
I don't think providing two distributions would be a great idea because at some point, there will be another plug-in that only uses something from KDE or GNOME and then we will need to bring those libraries to the other one.

What are the libraries required for this plug-in to work in ALL desktops?

Also, there is Darcula in all JetBrain products...wouldn't that be the same (or very close to)?

**Comment by weisJ** [comment]
> I don't think providing two distributions would be a great idea because at some point, there will be another plug-in that only uses something from KDE or GNOME and then we will need to bring those libraries to the other one.

I must admit I don't know very much about flatpak. Would it be possible to provide multiple distributions with different runtimes where the one with the most specialized runtime gets used i.e. On Gnome the gnome runtime on KDE the KDE runtime and everywhere else the Freedesktop runtime?

> What are the libraries required for this plug-in to work in ALL desktops?

The plugin currently only works on Gnome but may add support for KDE in the future. Currently its missing `giomm-2.4`.

> Also, there is Darcula in all JetBrain products...wouldn't that be the same (or very close to)?

I think you are misunderstanding the use of the plugin. It doesn't offer any theme by its own but rather synchronises the IDE theme with the OS. For the case of Gnome this involves interfacing with the Gnome settings through gio.

**Comment by oleid** [comment]
> I think you are misunderstanding the use of the plugin. It doesn't offer any theme by its own but rather synchronises the IDE theme with the OS. For the case of Gnome this involves interfacing with the Gnome settings through gio.

I'm not sure that this works due to sandboxing.

You can, however, run any flatpak app using a different runtime from command line, if you'd like to test:

`flatpak  run --runtime=org.gnome.Platform --runtime-version=40 com.jetbrains.Whatever`

Since both KDE and gnome platform are based on the freedesktop one, they should be compatible.

**Comment by xanscale** [comment]
you can change runtime manually, current freedesktop runtime not support this behaviour
